### ISSUE TITLE
Patch for SqlErrorLog.cs mismatched BeginExecuteXmlReader and EndExecuteReader

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Benknightdark/elmah#260]
```
Mismatched BeginExecuteXmlReader (at line 283) and EndExecuteReader (at line 
261).
```

Original issue reported on code.google.com by `george.c...@gmail.com` on 10 Nov 2011 at 10:02
- Merged into: #230

**Comment by GoogleCodeExporter** [comment]
```
First occured when I tried to "DOWNLOAD LOG" using ELMAH HTTP handler.
Full exception text:

System.InvalidOperationException: Mismatched end method call for asyncResult.  
Expected call to EndExecuteXmlReader but EndExecuteReader was called instead.
   at Elmah.ErrorLogDownloadHandler.AsyncResult.End() in \Elmah\src\Elmah\ErrorLogDownloadHandler.cs:line 535
   at Elmah.ErrorLogDownloadHandler.EndProcessRequest(IAsyncResult result) in \Elmah\src\Elmah\ErrorLogDownloadHandler.cs:line 138
   at System.Web.HttpApplication.CallHandlerExecutionStep.OnAsyncHandlerCompletion(IAsyncResult ar)


BeginExecuteXmlReader was being completed by calling EndExecuteReader. This 
patch replaces BeginExecuteXmlReader with BeginExecuteReader.
```

Original comment by `george.c...@gmail.com` on 10 Nov 2011 at 10:07

**Comment by GoogleCodeExporter** [comment]
```
I've just discovered, that this issue was fixed, but not yet released.
see: http://code.google.com/p/elmah/issues/detail?id=230

```

Original comment by `george.c...@gmail.com` on 11 Nov 2011 at 6:12

**Comment by GoogleCodeExporter** [comment]
Original comment by `jamesdriscoll71` on 12 Nov 2011 at 3:14
- Changed state: **Duplicate**
